### ISSUE TITLE
Landing Page resizing 

### ISSUE THREAD

**Issue by Aniket762** [Hackodisha/hackodisha-web#103]
Open the web application and then via inspect element check the responsiveness you can spot overflow of the map and content overlapping. And add some margin between the  2 buttons ie the Devfolio button and the Discord button. Do attach screenshots of the changes you have made in case you spot some more issues you can create an issue or reply back in the thread here.

**Comment by spapineau54** [comment]
is this issue still open? if so, i'd like to work on it if at all possible!

**Comment by Aniket762** [comment]
Yes, @spapineau54 it's still opened. Would love to see your contribution
