### ISSUE TITLE
Refactor sponsor section 

### ISSUE THREAD

**Issue by Aniket762** [Hackodisha/hackodisha-web#104]
Refactor the sponsor section of code in sponsors data and sponsors page. Define a parameter type as one key, in sponsor data in which the types can be platinum, gold, silver, and bronze. According to the type use map and filter to divide the sponsors in the following cards. In case of confusion feel free to reply in the thread would be more than happy to explain.

**Comment by mohankumar27** [comment]
@Aniket762  I would like to take up this issue ?

My understanding is presently **sponsors page** has all sponsors *[gold,sliver,platinum,bronze]* as separate elements. Instead you want those to be under a single map and based on sponsor type, you need those elements to be rendered. Is my understanding correct ?
