### ISSUE TITLE
Build folder

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#22]
Build folder should not exist in repo on Github. Please add it to `.gitignore` 😊

**Comment by Bartek532** [comment]
I think `.firebase` also should not been present in repo 😉

**Comment by sarah630** [comment]
Hey @Aniket762 , just adding the build folder in `.gitignore` will not remove it from git history. Even the `.firebase` folder needs to be removed. I would like to work on this issue. Hoping for a positive response ✌️

**Comment by Sonakshi1901** [comment]
> Build folder should not exist in repo on Github. Please add it to `.gitignore` 😊

Should I also add `.firebase` in `.gitignore`?

**Comment by Aniket762** [comment]
@Sonakshi1901 yes

**Comment by Sonakshi1901** [comment]
Ok done and pushed the codes.

**Comment by Sonakshi1901** [comment]
@Aniket762 I completely forgot to create a PR for this issue. Really sorry.

**Comment by sarah630** [comment]
Hey @Aniket762 @Sonakshi1901  is this work still remaining? Or done? I am still up for taking up the issue 🥂
