### ISSUE TITLE
[Feature] remove react-scroll

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#24]
**Problem**
Do we really need `react-scroll`?

**Idea**
Remove `react-scroll` and replace it with simple anchor links and `scroll-behavior: smooth` in CSS

**Notes**
https://gomakethings.com/smooth-scrolling-links-with-only-css/

**Comment by Sonakshi1901** [comment]
Yeah will do the changes.

**Comment by Sonakshi1901** [comment]
Sure. I'll do the necessary changes

**Comment by padmajabhol** [comment]
Interested

**Comment by Sonakshi1901** [comment]
@padmajabhol Cool I will just assign it to you.

**Comment by Bartek532** [comment]
Hi! Is this still open? I want to work on it 😁

**Comment by sumana2001** [comment]
@Bartek532 Yes you can go ahead 😁

**Comment by Bartek532** [comment]
Btw, we really need two files for navbar links? Responsiveness can be make with one file and media queries 😁 @sumana2001
