### ISSUE TITLE
[Bug] Provide meta description

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#25]
**To Reproduce**
Open page 😄

**Actual behavior**
Meta description is not provided, which has a bad impact on website.

**Expected behavior**
With meta description search engines have an easier task and they can confidently show the page in search results 😁

**Comment by Aniket762** [comment]
@Bartek532 can you please add the meta tags and send the PR, please. We have added meta with React Helmet but I guess it's not working. Will be great if you can help us out with the SEO 🥰

**Comment by Bartek532** [comment]
Ok, I will work on it 😁
