### ISSUE TITLE
[Bug] FAQ

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#26]
**Actual behavior**
In FAQ section questions are grouped in two columns, when user uncovers a few questions, the rows become asymmetrical and it looks not very good

**Expected behavior**
I think, better idea is to show questions (and answers 😁) in one column, one below the other, what do you think?

**Comment by Aniket762** [comment]
@Bartek532 we tried that bro but that wasn't looking that great so .. we choose this

**Comment by Aniket762** [comment]
Closing this issue dude hope you don't mind
