### ISSUE TITLE
Adding responsiveness to the buttons in homepage.

### ISSUE THREAD

**Issue by Sonakshi1901** [Hackodisha/hackodisha-web#32]
The buttons 'Apply' and 'Discord' have been created but it looks out of place in the mobile version. All you need to do is change the size of the buttons and add some margin to it. Make sure that the buttons are placed below the date.

**Comment by eddierayo-156** [comment]
I would like to try my hands on this if possible.

**Comment by padmajabhol** [comment]
Interested.

**Comment by Aniket762** [comment]
Hey, @eddierayo-156 go for it.  Attach the screenshots of the changes you made along with the PR

**Comment by eddierayo-156** [comment]
thank you. quick question, but how do you view the mobile version through localhost?

**Comment by Sonakshi1901** [comment]
@eddierayo-156 You right click and press inspect. After that on the top you can see responsive and when you click at it you can see a list of devices and their width. Click them and keep checking. For reference see the codes of other pages and you can learn to make the buttons responsive in a similar manner. (Hint: Use mediaqueries)

**Comment by Sonakshi1901** [comment]
@eddierayo-156 Is the task completed?
