### ISSUE TITLE
[Bug] Images without `alt`

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#38]
**To Reproduce**
Enter a page

**Actual behavior**
Some images don't have `alt` attribute, it's definitely a bug, even if the picture is only decorative `alt` must be present

**Expected behavior**
Add `alt` attribute to help e.g. screen readers to announce images correctly

**Notes**
Some example of bugged images: 
![image](https://user-images.githubusercontent.com/57185551/121570654-5c3afa80-ca22-11eb-89da-e5918acf1ab6.png)

**Comment by ahcodes** [comment]
@Bartek532 Hi, I would like to work on this issue, could you assign me please? Thanks!

**Comment by Bartek532** [comment]
Ok, go for it! 😁

**Comment by ahcodes** [comment]
@Bartek532 Which page did you find this bug? I went through almost all the pages and couldn't find ones without the `alt` attribute.

**Comment by Bartek532** [comment]
Hmm, I'm not sure, but I think the better idea is to inspect this on DevTools or test the website in some kind of validator 😉

**Comment by ahcodes** [comment]
I inspected it and saw that some images didn't have the `alt` attribute as you've mentioned but the thing is, the DevTools doesn't show me which file it is from. 

W3C's validator doesn't show any issues related to it, by the way.

**Comment by Bartek532** [comment]
I think the better idea is to inspect these images in React DevTools, where you can find components' names and many, many more 😛

**Comment by ahcodes** [comment]
Oh, you meant _that_ DevTools. I'm installing it on my browser. I currently know nothing about React, though.

**Comment by Bartek532** [comment]
Well, first, inspect in _normal_ DevTools and then change to React to get right component or search that component in project's files 😁

**Comment by ahcodes** [comment]
I kept looking but sorry, I just have no idea where it is.

**Comment by Bartek532** [comment]
I think you should have seen it before you pledged to do it 😔

**Comment by Sonakshi1901** [comment]
@Bartek532 I have added the `alt` attribute in the homepage images. After checking it you can close this issue.

**Comment by ahcodes** [comment]
> 
> 
> I think you should have seen it before you pledged to do it pensive

Thought contributions on GitHub (such as this) were acts of collaboration between the experienced and the learners. Guess I was wrong in this particular instance.

**Comment by Bartek532** [comment]
@ahcodes I gave you all the tips to do this task...

**Comment by Bartek532** [comment]
@Sonakshi1901 yep, it's perfectly fine now 😁

**Comment by Bartek532** [comment]
@Sonakshi1901 yep, it's perfectly fine now 😁
