### ISSUE TITLE
Images formats/sizes

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#40]
I think in our situation, when we are providing all images, we should properly prepare them. Serving them in appropriate format (e.g. WebP) and respectively size them can save seconds on page load!

**Comment by Sonakshi1901** [comment]
This task is done.

**Comment by Bartek532** [comment]
Hmm, I'm not sure about this, the images shouldn't be in more modern formats (e.g. WebP)? And for icons I think the best idea is to use vector graphics (SVG) 😁

**Comment by Sonakshi1901** [comment]
The images are in WebP (except for some because its difficult to convert).  So what's the issue?
