### ISSUE TITLE
[Feature] Make gold sponsors logo vertically centered

### ISSUE THREAD

**Issue by AabhasSao** [Hackodisha/hackodisha-web#41]
**Problem**
I think some logos are not vertically aligned to centered, doing so may look better aesthetically.

**Idea**
In each grid image should be centered vertically and horizontally.
what it should look like.
![Screenshot from 2021-06-11 22-57-54](https://user-images.githubusercontent.com/58210877/121726826-aeeee200-cb08-11eb-9a6a-83dbf2056f1f.png)

**Notes**
what it currently looks like
![Screenshot from 2021-06-11 22-50-51](https://user-images.githubusercontent.com/58210877/121726887-c75efc80-cb08-11eb-9ea0-5a8e305e7d92.png)

**Comment by AabhasSao** [comment]
Tell me if this feature looks useful, I'll work on it.

**Comment by sumana2001** [comment]
Sure go ahead @AabhasSao
