### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#49]
What do you think about adding `allcontributors` bot and section in README to the project? if you find the idea is good, I can take care of it 🥰 @Aniket762 @Sonakshi1901 @sumana2001

**Comment by Aniket762** [comment]
@Bartek532 go for it

**Comment by Bartek532** [comment]
@all-contributors please add @Bartek532 for a11y, bug, code, ideas and review

**Comment by Bartek532** [comment]
@all-contributors please add @Aniket762 for maintenance, mentoring, projectManagement, doc, code and content

**Comment by Bartek532** [comment]
@all-contributors please add @Sonakshi1901 for code, bug and ideas

**Comment by Bartek532** [comment]
@all-contributors please add @sumana2001 for code, bug and ideas

**Comment by Bartek532** [comment]
@all-contributors please add @sumana2001 for code, bug and ideas

**Comment by Bartek532** [comment]
@all-contributors please add @sumana2001 for code, bug and ideas

**Comment by Bartek532** [comment]
@Aniket762 I added and configure bot, if you can add the others contributors, thanks! 😁

**Comment by Aniket762** [comment]
@Bartek532 thanks, bro. The contributors whom you have added as good to go as of now let it be
