### ISSUE TITLE
[Code] Loop rendering

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#50]
I don't think it looks good:
https://github.com/Hackodisha/hackodisha-web/blob/main/src/pages/sponsors.jsx

It's definitely should be rendered in a loop to reduce redundant code.

`Tip: create an array with data and then use map method`

**Comment by Aniket762** [comment]
Yes, @Bartek53, this will help us to maintain the code and content ratio as well. I think it's a good idea. 

Ya, the data can be stored in JSON  format and then use props to render it in the application. Kinda make it like an API call and fetch all the data.

**Comment by padmajabhol** [comment]
Interested. Can you please assign me this task?

**Comment by padmajabhol** [comment]
> Yes, @bartek53, this will help us to maintain the code and content ratio as well. I think it's a good idea.
> 
> Ya, the data can be stored in JSON format and then use props to render it in the application. Kinda make it like an API call and fetch all the data.

Guess creating an array of objects while passing a unique ID to each, and then using props and mapping could do the job.

**Comment by Bartek532** [comment]
Ok, @padmajabhol go for it!
