### ISSUE TITLE
Use only one way to style components

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#62]
I think using different styles of styling in one project will be very difficult to read, so I suggest to rewrite all styles using only Styled Components 😁

**Comment by pallavi-1812** [comment]
Hello! Can I work on this issue?

**Comment by Bartek532** [comment]
@pallavi-1812 Ok, go for it! 😊

**Comment by pallavi-1812** [comment]
Thank you! Actually I have a doubt regarding styled components. Styled Components means I need to use styled-components library right?

**Comment by Bartek532** [comment]
Yep, but if you don't feel well with styled-components you can freely use CSS Modules too 😁

**Comment by pallavi-1812** [comment]
Ok. Thank you!
