### ISSUE TITLE
Cross-origin links

### ISSUE THREAD

**Issue by Bartek532** [Hackodisha/hackodisha-web#63]
Social media links are unsafe, so please add `rel="noopener"` or `rel="noreferrer"` to improve security and performance 🙂

**Comment by priyanshk20** [comment]
Can I do this task?

**Comment by Bartek532** [comment]
@priyanshk20 ok, go for it!

**Comment by priyanshk20** [comment]
Can I know which file I have to edit please?

**Comment by Bartek532** [comment]
Footer 😁

https://github.com/Hackodisha/hackodisha-web/tree/main/src/components/footer

**Comment by priyanshk20** [comment]
@Bartek532 Made a PR. Please Review.
