### ISSUE TITLE
Add light mode 

### ISSUE THREAD

**Issue by Aniket762** [Hackodisha/hackodisha-web#7]
Add a button in the navbar such that when toggled light mode and dark mode can be fetched.  You can get the blobs from the zip file attached below. And use that while developing the light mode background. Not necessarily white but any light color which you think will look good feel free to implement. No need to making any branches create the PR for the main branch. 

[blobs.zip](https://github.com/Hackodisha/hackodisha-web/files/6506886/blobs.zip)

Please do attach a gif or screenshots on how does it look after making the changes😎

**Comment by vishal78689** [comment]
I would like to work on this.

**Comment by Aniket762** [comment]
Hey @vishal78689 go for it

**Comment by smalawad** [comment]
Shall upload PR for this?

**Comment by Aniket762** [comment]
Hey @smalawad I guess @vishal78689 is working on it currently in case he does not send a Pull Request or comments back to you, you can send yours.

**Comment by Aniket762** [comment]
hey, @smalawad do you still want to work on it? Would love to see your contribution 🥰

**Comment by eddierayo-156** [comment]
If it's still possible, I would like to try to resolve this issue.
