### ISSUE TITLE
Create and add 4 cards in the Prizes page

### ISSUE THREAD

**Issue by Sonakshi1901** [Hackodisha/hackodisha-web#70]
Tasks to do:

- [ ] Create a separate card component which would display the details when a cursor is brought to it.
- [ ] Put it in a loop and display it 4 times in the Prize section in a grid format (ideally 4 in one row).

Do share your ideas as screenshots and mention the animations you would use.

**Comment by manjeetdhayal** [comment]
I want to work on this issue.

**Comment by Aniket762** [comment]
@manjeetdhayal go for it!

**Comment by manjeetdhayal** [comment]
## PR  #88 has been created for this issue 
I am attaching some snippets of the prize section below. 


![prize_img1](https://user-images.githubusercontent.com/76167344/125944396-fda8d2b9-a453-4c7f-8720-d25a6addc284.png)
![prize_img2](https://user-images.githubusercontent.com/76167344/125944408-d3c0cdc7-a645-468b-b879-c48b892cd82a.png)
![prize_img3](https://user-images.githubusercontent.com/76167344/125944433-87488186-5358-4ff7-aa4b-6201a55c81e4.png)
![prize_img4](https://user-images.githubusercontent.com/76167344/125944450-62570e51-c0ae-494e-8eaf-f45d9c3f9477.png)

**Comment by Aniket762** [comment]
@manjeetdhayal this looks great can you please send the PR?

**Comment by debasish-creator** [comment]
#88 prizes section added
