### ISSUE TITLE
Popup button for all the track cards

### ISSUE THREAD

**Issue by Sonakshi1901** [Hackodisha/hackodisha-web#77]
The cards in the tracklist do not have any additional info about them.

- [ ] Create a "Know more" button 
- [ ] Create a popup that shows the info for all the track cards using material UI or an npm package.

**Comment by debasish-creator** [comment]
Interested

**Comment by jmurphy5613** [comment]
I'm currently working on this!

**Comment by jmurphy5613** [comment]
Has this been solved yet?

**Comment by Aniket762** [comment]
@jmurphy5613 not yet. Go for it

**Comment by jmurphy5613** [comment]
I looked in the code and saw something related to this, but I'll go for it

**Comment by jmurphy5613** [comment]
I sent in a pull request for the first part of the issue
